#!/usr/bin/env python3

class Solution:
    def countNegatives(self, grid: List[List[int]]) -> int:
        
        count = 0

        for row in grid:
            left, right = 0, len(row)
            while left < right:
                mid = (left + right) // 2
                if row[mid] >= 0:
                    left = mid + 1
                else:
                    right = mid
            count += len(row) - right
        
        return count
