#!/usr/bin/env python3#!/usr/bin/env python3

class Solution:
    def areOccurrencesEqual(self, s: str) -> bool:

        """
        count = s.count(s[0])
        for ch in s:
            #print(ch, s.count(ch))
            if s.count(ch) != count: return False
        return True
        """

        #print(collections.Counter(s).values())
        #print(set(collections.Counter(s).values()))
        return len(set(Counter(s).values())) == 1
