#!/usr/bin/env python3

class Solution:
    def checkValid(self, matrix: List[List[int]]) -> bool:

        check = []
        for i in range(1, len(matrix) + 1):
            check.append(i)
        
        for i in range(len(matrix)):
            #rows
            uniq = set(matrix[i])
            if len(uniq) != len(matrix) or list(uniq)[0] != 1 or list(uniq)[-1] != len(matrix): return False
            #columns
            col = []
            for row in matrix:
                col.append(row[i])
            uc = set(col) #uniq column entries
            if len(uc) != len(matrix) or list(uc)[0] != 1 or list(uc)[-1] != len(matrix): return False
        return True
