#!/usr/bin/env python3

class Solution:
    def strongPasswordCheckerII(self, password: str) -> bool:

        if len(password) < 8: return False
        low, up, dg, sp = 0,0,0,0
        last = None
        for i in range(len(password)):
            ch = password[i]
            if ch.islower(): low += 1
            if ch.isupper(): up += 1
            if ch.isdigit(): dg += 1
            if ch in "!@#$%^&*()-+": sp += 1
            if ch == last: return False #storing last ch rather than comparing idx i with i+1 each time... moved code upto 98.7% on runtime
            last = ch
        if low == 0 or up == 0 or dg == 0 or sp == 0:
            return False
        return True
