#!/usr/bin/env python3

class Solution:
    def zeroFilledSubarray(self, nums: List[int]) -> int:

        count = 0
        i = 0

        while i < len(nums):
            if nums[i] == 0:
                p = i
                consec = 1
                count += 1
                while p + 1 < len(nums):
                    p += 1
                    if nums[p] == 0:
                        consec += 1
                        count += consec
                    else:
                        i = p + 1
                        break
                i = p + 1
            else:
                i += 1
        return count
