#!/usr/bin/env python3

class Solution:
    def partitionString(self, s: str) -> int:

        d = {}
        subs = 1
        for i in range(len(s)):
            if s[i] not in d:
                d[s[i]] = 1
            else:
                d = {s[i]:1}
                subs += 1
        return subs
