#!/usr/bin/env python3

class Solution:
    def countTime(self, times: str) -> int:

        any = "?"
        if times[0] in any and times[1] in any: hours = 24
        elif times[0] in any and times[1] not in any: 
            if int(times[1]) < 4: hours = 3
            else: hours = 2
        elif times[0] not in any and times[1] not in any: hours = 1
        else:
            if times[0] == "2": hours = 4
            else: hours = 10

        if times[3] in any and times[4] in any: mins = 60
        elif times[3] not in any and times[4] not in any: mins = 1
        elif times[3] in any and times[4] not in any: mins = 6
        else: mins = 10

        return hours * mins



        
