#!/usr/bin/env python3

# beats 97.51% on runtime

class Solution:
    def applyOperations(self, nums: List[int]) -> List[int]:

        idx = 0
        ans = []
        zero = []
        while idx < len(nums):
            num = nums[idx]
            next = None
            if idx + 1 < len(nums):
                next = nums[idx + 1]
            if num == next:
                num *= 2
                if num > 0: ans.append(num)
                else: zero.append(num)
                zero.append(0)
                idx += 2
            else:
                if num > 0: ans.append(num)
                else: zero.append(num)
                idx += 1
        return ans + zero
            

