#!/usr/bin/env python3

class Solution:
    def minMaxDifference(self, num: int) -> int:

        #max will change first non9 to 9
        #min will change first non0 to 0
        num1 = num2 = num

        idx = 0
        maxnum = str(num)
        flag = None
        while flag == None and idx < len(maxnum):
            if maxnum[idx] != "9":
                digit = maxnum[idx]
                flag = 1
                num1 = maxnum.replace(digit, "9")
            else: idx += 1

        idx = 0
        minnum = str(num)
        flag = None
        while flag == None and idx < len(minnum):
            if minnum[idx] != "0":
                digit = minnum[idx]
                flag = 1
                num2 = minnum.replace(digit, "0")
            else: idx += 1

        return int(num1)-int(num2)
        
