#!/usr/bin/env python3

class Solution:
    def mergeArrays(self, nums1: List[List[int]], nums2: List[List[int]]) -> List[List[int]]:

        new, p, end = [], 0, max(nums1[-1][0], nums2[-1][0])
        #print("end:",end)
        while p <= end:
            #print('p:',p)
            flag = None
            val = 0
            if len(nums1) > 0 and nums1[0][0] == p:
                flag = 1
                val += nums1[0][1]
                nums1.pop(0)
                #print("val:",val)
            if len(nums2) > 0 and nums2[0][0] == p:
                flag = 1
                val += nums2[0][1]
                nums2.pop(0)
                #print("val:",val)
            if flag == 1:
                new.append([p, val])
                #print("append val:",val)
            p += 1
        return new
