#!/usr/bin/env python3

class Solution:
    def findDelayedArrivalTime(self, arrivalTime: int, delayedTime: int) -> int:

        ans = arrivalTime + delayedTime
        if ans >= 24: ans -= 24
        return ans
