#!/usr/bin/env python3

class Solution:
    def hammingDistance(self, x: int, y: int) -> int:

        ans = 0
        bx, by = bin(x)[2:], bin(y)[2:]

        dif = abs(len(bx) - len(by))
        if dif != 0:
            if len(bx) < len(by):
                bx = "0" * dif + bx
            else:
                by = "0" * dif + by

        for i in range(len(bx)):
            if bx[i] != by[i]: ans += 1

        return ans
