#!/usr/bin/env python3

class Solution:
    def selfDividingNumbers(self, left: int, right: int) -> List[int]:

        def selfDiv(num):
            for ch in str(num):
                if ch == "0": return False
                if num % int(ch) != 0: return False
            return True

        output = []
        for n in range(left, right +1):
            if selfDiv(n): output.append(n)

        return output
