#!/usr/bin/env python3

class Solution:
    def canPlaceFlowers(self, flowerbed: List[int], n: int) -> bool:

        count = 0
        prev = 0
        for i in range(len(flowerbed)):
            if flowerbed[i] == 0 and prev == 0 and (
                i == len(flowerbed) -1 or flowerbed[i+1] == 0):
                count += 1
                prev = 1
            else: prev = flowerbed[i]
        return count >= n
