#!/usr/bin/env python3

class Solution:
    def maxArea(self, height: List[int]) -> int:

        best = 0 # max area
        p1 = 0
        p2 = len(height) -1
        while p1 < p2:
            area = min(height[p1], height[p2]) * (p2 - p1)
            if area > best:
                best = area        
            if height[p1] < height[p2]:
                p1 += 1
            else:
                p2 -= 1
        return best
