#!/usr/bin/env python3

class Solution:
    def firstUniqChar(self, s: str) -> int:
        
        default = -1
        d = {}
        for ch in s:
            if ch in d:
                d[ch] += 1
            else:
                d[ch] = 1
        for i in range(len(s)):
            if d[s[i]] == 1:
                return i
        return default
        
