#!/usr/bin/env python3

class Solution:
    def minEatingSpeed(self, piles: List[int], h: int) -> int:

        l, r = 1, max(piles)

        def enoughTime(rate, time):  
            hrs = 0 
            for p in piles:
                if p % rate == 0:
                    hrs += p / rate
                else:
                    hrs += p // rate + 1
            return hrs <= time

        while l < r:
            mid = (l + r) // 2 
            if enoughTime(mid, h):
                r = mid 
            else:
                l = mid + 1
        return l

            

