#!/usr/bin/env python3

class Solution:
    def lengthOfLongestSubstring(self, s: str) -> int:

    # Given a string s, find the length of the longest substring without repeating characters.  

    # use sliding window, O(n) time complexity

        d = {}
        left, right = 0, 0
        counter = 0

        while left < len(s) and right < len(s):
            char = s[right]
            if char in d:
                left = max(left, d[char] +1)
            d[char] = right
            counter = max(counter, (right - left +1))
            right += 1

        return counter

        # thanks coderrman
        # https://leetcode.com/problems/longest-substring-without-repeating-characters/solutions/3226240/best-solution-explained-with-illustrations/
