#!/usr/bin/env python3

class Solution:
    def lengthOfLongestSubstring(self, s: str) -> int:

        d, count, left, right = {}, 0, 0, 0

        while left < len(s) and right < len(s):
            ch = s[right]
            if ch in d:
                left = max(left, d[ch] + 1)
            d[ch] = right
            right += 1
            count = max(count, right - left)

        return count
