#!/usr/bin/env python3

class Solution:
    def minimumTime(self, time: List[int], totalTrips: int) -> int:

        while True:

            if len(time) == 1:
                return time[0]

            left = min(time)  # min time
            right = min(time) * totalTrips  # max time
            given_time = (right + left) // 2   # mid point

            trips = 0
            possible = []
            impossible = []

            for bus in time:
                trips += given_time // bus

            if trips >= totalTrips:
                if trips - 1 in impossible:
                    return trips
                possible = trips
                right = given_time 
                trips = 0
            else:
                if trips + 1 in possible:
                    return trips + 1
                impossible = trips
                left = given_time + 1
                trips = 0
        


        
