#!/usr/bin/env python3

class Solution:
    def missingNumber(self, nums: List[int]) -> int:

        nums.sort()
        l = 0
        r = len(nums)

        while l < r:
            m = (l+r) // 2
            if nums[m] == m:
                l = m+1
            else:
                r = m
        return l
