#!/usr/bin/env python3

class Solution:
    def reverse(self, x: int) -> int:

        if str(x)[0] == "-":
            rev = int(str(x)[:0:-1])*(-1)
        else:
            rev = int(str(x)[::-1])
        if rev >= -2**31 and rev <= 2**31 - 1:
            return rev
        return 0
