#!/usr/bin/env python3

class Solution:
    def reverseWords(self, s: str) -> str:

        newstring = ""    

        for word in s.split():
            ls = list(word)
            l, r = 0, len(word) -1
            
            while l < r:
                ls[l], ls[r] = ls[r], ls[l]
                l += 1
                r -= 1

            newstring += "".join(ls) + " "

        return newstring[:-1]
