#!/usr/bin/env python3

class Solution:
    def romanToInt(self, s: str) -> int:
        d = {"I":1, "V":5, "X":10, "L":50, "C":100, "D":500, "M":1000}
        ct = 0
        for i in range(len(s)):
            ct += d[s[i]]
            if i < len(s) -1:
                if s[i] == "I":
                    if s[i+1] == "V" or s[i+1] == "X":
                        ct -= 2 * d[s[i]]
                if s[i] == "X":
                    if s[i+1] == "L" or s[i+1] == "C":
                        ct -= 2 * d[s[i]]
                if s[i] == "C":
                    if s[i+1] == "D" or s[i+1] == "M":
                        ct -= 2 * d[s[i]]
        return ct
