#!/usr/bin/env python3

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def isSameTree(self, p: Optional[TreeNode], q: Optional[TreeNode]) -> bool:

        # base cases 
        if not p and not q: return True # because identically empty
        if not p or not q: return False 
        if p.val != q.val: return False

        # then recursive dfs
        return (self.isSameTree(p.left, q.left) 
                and self.isSameTree(p.right, q.right)) # returns True if both of these recursions is True, else False
                # thanks Neetcode youtube channel
