#!/usr/bin/env python3

class Solution:
    def searchInsert(self, nums: List[int], target: int) -> int:

        if target > nums[-1]:
            return len(nums)

        l, r = 0, len(nums)-1

        def isUnder(mid):
            return target <= nums[mid] 

        while l < r:
            mid = (l+r)//2

            if isUnder(mid):
                r = mid
            else:
                l = mid +1
        return l
