#!/usr/bin/env python3

class Solution:
    def search(self, nums: List[int], target: int) -> int:
        
        start = 0
        for i in range(len(nums)):
            if nums[i] < nums[i - 1]:
                start = i
                break

        ls = nums[start:] + nums[:start]

        left, right = 0, len(nums)
        # print(ls)

        while left < right:
            mid = (left + right) // 2
            if ls[mid] == target:
                if mid + start < len(nums):
                    return mid + start
                else:
                    return mid + start - len(nums)

            if ls[mid] > target:
                right = mid
            else:
                left = mid + 1
        return -1



