#!/usr/bin/env python3

class Solution:
    def sortedSquares(self, nums: List[int]) -> List[int]:

        """
        for i in range(len(nums)):
            nums[i] = nums[i]**2
        return sorted(nums)
        """

        return sorted(x**2 for x in nums)
        
