#!/usr/bin/env python3

class Solution:
    def mySqrt(self, x: int) -> int:

        l = 1
        r = x

        while l != r:
            mid = (l+r) //2
            if mid*mid <= x and (mid+1)*(mid+1) > x:
                return mid
            if mid * mid > x:
                r = mid
            else:
                l = mid
        return l
    
