#!/usr/bin/env python3

class Solution:
    def threeSumClosest(self, nums: List[int], target: int) -> int:

        #ans = [nums[0],nums[1],nums[2]] # init
        best = nums[0]+nums[1]+nums[2] # init
         
        nums.sort()
        for i, v in enumerate(nums):
            if i > 0 and v == nums[i-1]:
                continue
            
            l,r = i+1, len(nums)-1

            while l < r:
                sum3 = v + nums[l] + nums[r]

                if sum3 - target == 0:
                    best = sum3
                    #ans = [v, nums[l], nums[r]]
                    return best

                elif abs(sum3 - target) < abs(best - target):
                    best = sum3
                    #ans = [v, nums[l], nums[r]]
                   
                if sum3 > target:
                    r -= 1
                else:
                    l += 1

        return best
