#!/usr/bin/env python3

class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:

        d = {} 
        for i in range(len(nums)): 
            c = target - nums[i]
            if c in d:
                return i, d[c]
            d[nums[i]] = i 

        # Runtime 56 ms Beats 94.68%
        # Memory 15 MB Beats 58.41%


        

